# Generated by Django 4.2.3 on 2023-07-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('ActualPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Sold_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_At', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='selling_status',
        ),
        migrations.DeleteModel(
            name='stock_available',
        ),
    ]
